### ISSUE TITLE
SMSC agument problem

### ISSUE THREAD

**Issue by Tailwhip** [mgaman/PDUlib#25]
Hi,

I'm writting multipart SMS sender using PDU mode.
From my understanding SMSC is an optional parameter (in this video multipart message has been sent without passing smsc: https://www.youtube.com/watch?v=wku1401Mc1w&t=765s)
Unfortunatelly pdulib encode method don't support multipart message encoding without smsc argument (returns -1), so I've decided to provide smsc gathered from modem using "AT+CSCA?" command. 
But what my modem gives me as smsc is just a 11 characters phone number, like: +48123456789 and It simply cannot be used as unsigned short smsc argument because it's simply too long.

My question is: is there any way to encode multipart message without using smsc, or where can I find smsc matching encode method argument?
I'm sorry for my lack of knowledge but I'm just new to GSM modules.
Thank you in advance!

Best regards

**Comment by mgaman** [comment]
Hi,
I assume that SMSC means the SCA part of the message. It is NOT optional. Without it you cannot send an SMS.
Note that SMS is a store and forward mechanism. An SMS does not go directly from your phone to the target. It goes from your phone to the service centre (SCA) and from there to the target.
Phone numbers are alphanumeric strings, not integers. The AT+CSCA? command returns a string which is used, as is, in the setSCAnumber method. The leading '+' character (if any) means that the phone number is in international format. Lack of a leading '+' means that it is in national format.
Hope this helps.

**Comment by SherifMEldeeb** [comment]
Excuse me I guess what the OP meant that the PDU can have the first Octet as 00 indicating the default SCA for the connected network as stated by this reference "http://rfc.nop.hu/sms/default.htm" Sending Section.
