### ISSUE TITLE
decodePDU is case sensitive

### ISSUE THREAD

**Issue by spcbowen** [mgaman/PDUlib#27]
The *pdu parameter into decodePDU expects an upper case hex string.

My modem (SIM A7608E) returns lowercase hex from +CMT: notifications, resulting in a garbled text output.

This may not be considered a bug in pdulib, but it may be worth putting a note in the readme to save someone as slow as me a whole day of debugging!

Fantastic work otherwise... thanks for sharing!

**Comment by mgaman** [comment]
Thanks for the feedback. Looks like a trivial fix so I'll get on to it .
