### ISSUE TITLE
All parts of a multipart encoded message are prepended with a space

### ISSUE THREAD

**Issue by baskluiters** [mgaman/PDUlib#36]
When encoding multipart messages, every part has a prepended space. 
Also when a multipart with 1 parts is encoded, the space is prepended.
Verified on my smart phone by observing the received SMS
Verified using the encoded string on https://www.smspdu.be; by viewing the HTML source you also see the prepended space

Using version 0.5.7 (also tested with 0.5.5: same result)

**Comment by mgaman** [comment]
Please send me the PDU strings

**Comment by baskluiters** [comment]
This is the PDU string of the string `rabbit` (without a leading space).

```07911356000000F341000B911326000000F000000E0500032A010140F2B0589CA603```

**Comment by mgaman** [comment]
I've just looked into this and I found that the bug occurs when sending a multi-part GSM7 bit message with a reference number < 255. 
A work around is to provide a reference number > 255. 
Please do this until I fix the bug.

**Comment by baskluiters** [comment]
Ok Thanks

**Comment by mgaman** [comment]
Fixed in release 0.5.9
