### ISSUE TITLE
Compiler complains on fallthrough

### ISSUE THREAD

**Issue by baskluiters** [mgaman/PDUlib#37]
Compiler for ESP32 in PlatformIO complains on fallthrough
```
.pio/libdeps/esp32dev/pdulib/src/pdulib.cpp: In member function 'int PDU::decodeAddress(const char*, char*, eLengthType)':
.pio/libdeps/esp32dev/pdulib/src/pdulib.cpp:963:22: warning: attribute 'fallthrough' not preceding a case label or default label
       [[fallthrough]];
                      ^
```
Removing the semicolon (;) after `[[fallthrough]]` seems to fix the issue.
Using 0.5.7

**Comment by mgaman** [comment]
This is not a bug, see issue #26 in Readme.
If the user chooses to implement Network Specific Numbers and uncomments  the <b>case 3:</b> line then the warning goes away.
