### ISSUE TITLE
Decode the outgoing message captured via serial, coming from a centralized system

### ISSUE THREAD

**Issue by AntonioRiccelli77** [mgaman/PDUlib#38]
Hi

I would need to decode the GSM 3.38 message sent from a centralized system because I need to make integrations with it.
the example message that the system sends is like this;

02919311000181F000000B3EC7690B0683C1603250D04D7FBBD36F90343D1E97D9EC34A8EA02F15A31182C3693C560329B6C46F3815A20282C060ACACBE11808454C01

however the library does not decode outgoing messages.
how can i fix this?

Thank you
Antonio

**Comment by mgaman** [comment]
On further examination I see that a zero length sender number is legal, but there is more. The timestamp field is odd,  the timezone field is 0x69 i.e. 105 whereas the maximum possible is 95.
Please send me the expected content and I'll try to work it out from there

**Comment by AntonioRiccelli77** [comment]
Hello
in reality I only need a decoder that translates the hex strings from gsm 7 into readable text, I don't need to know the sender or recipient number, I only have to decode the TP-UD of the message leaving out all the rest.
I don't know if this is possible, but this is all I need.

**Comment by mgaman** [comment]
I just got around to properly examining this and realised that I hadn't really understood the problem.
Sorry about that and ignore my reply from Feb 21.
My code only decodes SMS-DELIVER messages and yours, as you say is SMS-SUBMIT.
